module("LvLed_Recipes", package.seeall)

RecipeUnlock  = 
{
	{ Recipe = "dyworld-greenhouse", Level = 2, type = 3 },
	{ Recipe = "dyworld-wood-creation-1", Level = 2, type = 1 },
	{ Recipe = "dyworld-wood-seed", Level = 2},
	{ Recipe = "dyworld-wood-creation-2", Level = 9, type = 1 },
	{ Recipe = "dyworld-sugar", Level = 6 },
	{ Recipe = "dyworld-flour", Level = 5 },
	{ Recipe = "dyworld-bread", Level = 5 },
	{ Recipe = "dyworld-wheat", Level = 4 },
	{ Recipe = "dyworld-wheat-seed", Level = 4 },
	{ Recipe = "dyworld-carrot", Level = 3 },
	{ Recipe = "dyworld-recycler", Level = 4, type = 3 },
	{ Recipe = "centrifuge", Level = 2, type = 3 },
	{ Recipe = "dyworld-water-seperation-1", Level = 2, type = 1 },
	{ Recipe = "dyworld-water-seperation-2", Level = 2, type = 1 },
	{ Recipe = "dyworld-sludge-seperation", Level = 2, type = 1 },
	{ Recipe = "dyworld-acid-seperation", Level = 2, type = 1 },
	{ Recipe = "dyworld-fertilizer-seperation", Level = 8, type = 1 },
	{ Recipe = "dyworld-basic-clean-oil-processing", Level = 5, type = 1 },
	{ Recipe = "dyworld-advanced-clean-oil-processing", Level = 8, type = 1 },
	{ Recipe = "dyworld-wheat-farming-2", Level = 9 },
	{ Recipe = "dyworld-carrot-farming-2", Level = 9 },
	{ Recipe = "flamethrower-turret", Level = 20 },
	{ Recipe = "heavy-armor", Level = 10 },
	{ Recipe = "modular-armor", Level = 25 },
	{ Recipe = "power-armor", Level = 50 },
	{ Recipe = "power-armor-mk2", Level = 75 },
}