# Determines if we search the title (optional). Defaults to true.
matchTitle: true

# Determines if we search the body (optional). Defaults to true.
matchBody: true

# Determines if label matching is case sensitive (optional). Defaults to true.
caseSensitive: false

# Explicit keyword mappings to labels. Form of match:label. Required.
labelMappings:
  rework: rewrite
  bug: bug
  error: bug
  crash: bug
  conflict: bug
  balance: balancing
  add: new feature
  graphics: graphics
  texture: graphics
  textures: graphics
  intended: wontfix/feature
  restructure: rewrite
