
DyWorld_2_Main_Tech = {
    --[""] = {},

    -- Start of the game --
    ["combat"] = {},
    ["metallurgy"] = {},
    ["biological"] = {},
    ["production-1"] = {},
    ["infrastructure"] = {},
    ["automation"] = {},

    -- Metallurgy --
    --- Ore Processing ---
    ["ore-processing-1"] = {"metallurgy"},
    ["ore-processing-2"] = {"metal-processing-1"},
    ["ore-processing-3"] = {"metal-processing-2"},
    ["ore-processing-4"] = {"metal-processing-3"},
    ["ore-processing-5"] = {"metal-processing-4", "space-technology"},
    --- Metal Processing ---
    ["metal-processing-1"] = {"alloying-1"},
    ["metal-processing-2"] = {"alloying-2"},
    ["metal-processing-3"] = {"alloying-3"},
    ["metal-processing-4"] = {"alloying-4"},
    ["metal-processing-5"] = {"alloying-5"},
    --- Alloying ---
    ["alloying-1"] = {"ore-processing-1"},
    ["alloying-2"] = {"ore-processing-2"},
    ["alloying-3"] = {"ore-processing-3"},
    ["alloying-4"] = {"ore-processing-4"},
    ["alloying-5"] = {"ore-processing-5"},
    --- Main Ore Processing ---
    ["carbon-processing-1"] = {"ore-processing-1"},
    ["carbon-processing-2"] = {"carbon-processing-1", "ore-processing-2"},
    ["carbon-processing-3"] = {"carbon-processing-2", "ore-processing-3"},
    ["carbon-processing-4"] = {"carbon-processing-3", "ore-processing-4"},
    ["carbon-processing-5"] = {"carbon-processing-4", "ore-processing-5"},
    ["hematite-processing-1"] = {"ore-processing-1"},
    ["hematite-processing-2"] = {"hematite-processing-1", "ore-processing-2"},
    ["hematite-processing-3"] = {"hematite-processing-2", "ore-processing-3"},
    ["hematite-processing-4"] = {"hematite-processing-3", "ore-processing-4"},
    ["hematite-processing-5"] = {"hematite-processing-4", "ore-processing-5"},
    ["chalcopyrite-processing-1"] = {"ore-processing-1"},
    ["chalcopyrite-processing-2"] = {"chalcopyrite-processing-1", "ore-processing-2"},
    ["chalcopyrite-processing-3"] = {"chalcopyrite-processing-2", "ore-processing-3"},
    ["chalcopyrite-processing-4"] = {"chalcopyrite-processing-3", "ore-processing-4"},
    ["chalcopyrite-processing-5"] = {"chalcopyrite-processing-4", "ore-processing-5"},
    --- Secondary Ore Processing ---
    ["iron-processing-1"] = {"hematite-processing-1"},
    ["iron-processing-2"] = {"iron-processing-1", "ore-processing-2"},
    ["iron-processing-3"] = {"iron-processing-2", "ore-processing-3"},
    ["iron-processing-4"] = {"iron-processing-3", "ore-processing-5"},
    ["copper-processing-1"] = {"chalcopyrite-processing-1"},
    ["copper-processing-2"] = {"copper-processing-1", "ore-processing-2"},
    ["copper-processing-3"] = {"copper-processing-2", "ore-processing-3"},
    ["copper-processing-4"] = {"ore-processing-5", "copper-processing-3"},
    ["tin-processing-1"] = {"ore-processing-1"},
    ["tin-processing-2"] = {"tin-processing-1", "ore-processing-2"},
    ["tin-processing-3"] = {"tin-processing-2", "ore-processing-3"},
    ["tin-processing-4"] = {"tin-processing-3", "ore-processing-5"},
    ["zinc-processing-1"] = {"ore-processing-1"},
    ["lead-processing-1"] = {"ore-processing-1"},
    ["silver-processing-1"] = {"ore-processing-3"},
    ["silver-processing-2"] = {"silver-processing-1", "ore-processing-4"},
    ["silver-processing-3"] = {"silver-processing-2", "ore-processing-5"},
    ["gold-processing-1"] = {"ore-processing-3"},
    ["gold-processing-2"] = {"gold-processing-1", "ore-processing-4"},
    ["gold-processing-3"] = {"gold-processing-2", "ore-processing-5"},
    ["aluminium-processing-1"] = {"ore-processing-1"},
    ["titanium-processing-1"] = {"ore-processing-3"},
    ["titanium-processing-2"] = {"titanium-processing-1", "ore-processing-4"},
    ["titanium-processing-3"] = {"titanium-processing-2", "ore-processing-5"},
    ["tungsten-processing-1"] = {"ore-processing-4"},
    ["tungsten-processing-2"] = {"ore-processing-5", "tungsten-processing-1"},
    --- Alloys ---
    ["bronze-alloying-1"] = {"alloying-1"},
    ["bronze-alloying-2"] = {"alloying-2", "bronze-alloying-1"},
    ["bronze-alloying-3"] = {"bronze-alloying-2", "alloying-3"},
    ["steel-processing"] = {"metal-processing-1"},
    ["steel-processing-2"] = {"steel-processing", "metal-processing-2"},
    ["steel-alloying-1"] = {"alloying-1"},
    ["steel-alloying-2"] = {"alloying-2", "steel-alloying-1"},
    ["steel-alloying-3"] = {"alloying-3", "steel-alloying-2"},
    ["brass-alloying-1"] = {"alloying-1"},
    ["brass-alloying-2"] = {"alloying-2", "brass-alloying-1"},
    ["brass-alloying-3"] = {"brass-alloying-2", "alloying-3"},
    ["brass/bronze-processing-1"] = {"metal-processing-1"},
    ["brass/bronze-processing-2"] = {"brass/bronze-processing-1", "metal-processing-2"},
    ["stainless-steel-alloying-1"] = {"steel-alloying-2"},
    ["stainless-steel-alloying-2"] = {"steel-alloying-3", "stainless-steel-alloying-1"},
    ["stainless-steel-processing-1"] = {"steel-processing-2"},

    -- Combat/Warfare/Military --
    ["military"] = {"combat"},
    ["military-2"] = {"military"},
    ["military-3"] = {"military-2"},
    ["military-4"] = {"military-3"},
    ["military-5"] = {"military-4", "space-technology"},
    ["equipment"] = {"combat"},
    ["support"] = {"equipment"},
    ["defence"] = {"equipment"},
    ["attack"] = {"equipment"},
    --- Armor ---
    ["heavy-armor"] = {"optics", "equipment"},
    ["modular-armor"] = {"heavy-armor", "military-2"},
    ["power-armor"] = {"modular-armor", "military-3"},
    ["power-armor-mk2"] = {"power-armor", "military-5"},
    --- Equipment ---
    ["energy-shield-equipment"] = {"titanium-processing-2", "gold-processing-2", "battery-equipment", "defence"},
    ["night-vision-equipment"] = {"silver-processing-1", "battery-equipment"},
    ["belt-immunity-equipment"] = {"solar-panel-equipment", "iron-processing-2", "support"},
    ["solar-panel-equipment"] = {"solar-energy", "tin-processing-1", "support"},
    ["personal-laser-defense-equipment"] = {"energy-shield-equipment", "battery-mk2-equipment", "attack"},
    ["energy-shield-mk2-equipment"] = {"energy-shield-equipment", "battery-mk2-equipment", "fusion-reactor-equipment"},
    ["battery-equipment"] = {"silver-processing-1", "solar-panel-equipment"},
    ["battery-mk2-equipment"] = {"battery-equipment"},
    ["fusion-reactor-equipment"] = {"nuclear-power", "solar-panel-equipment", "tungsten-processing-1"},
    ["exoskeleton-equipment"] = {"belt-immunity-equipment", "titanium-processing-1"},
    ["personal-roboport-equipment"] = {"logistic-robots",  "construction-robots", "battery-equipment", "support"},
    ["personal-roboport-mk2-equipment"] = {"logistic-system", "personal-roboport-equipment"},

    -- Logistic --
    ["logistics"] = {"infrastructure"},
    ["logistics-2"] = {"logistics"},
    ["logistics-3"] = {"logistics-2"},
    ["logistics-4"] = {"logistics-3"},
    ["logistics-5"] = {"space-technology", "logistics-4"},
    ["transportation-1"] = {"infrastructure"},
    ["transportation-2"] = {"transportation-1"},
    ["transportation-3"] = {"transportation-2"},
    ["transportation-4"] = {"transportation-3"},
    ["transportation-5"] = {"transportation-4"},

    -- Power --
    ["power-1"] = {"infrastructure", "automation"},
    ["power-2"] = {"power-1"},
    ["power-3"] = {"power-2"},
    ["power-4"] = {"power-3"},
    ["power-5"] = {"space-technology", "power-4"},
    ["solar-energy"] = {"electric-energy-accumulators", "advanced-electronics"},
    ["electric-energy-accumulators"] = {"power-2"},
    ["electric-energy-distribution-1"] = {"power-1"},
    ["electric-energy-distribution-2"] = {"electric-energy-distribution-1", "power-2"},

    -- Automation --
    ["automation-2"] = {"automation"},
    ["automation-3"] = {"automation-2"},
    ["automation-4"] = {"automation-3"},
    ["automation-5"] = {"automation-4", "space-technology"},
    ["production-2"] = {"production-1"},
    ["production-3"] = {"production-2"},
    ["production-4"] = {"production-3"},
    ["production-5"] = {"production-4", "space-technology"},
    ["advanced-material-processing"] = {"production-2"},
    ["advanced-material-processing-2"] = {"production-3"},
    --- Oil ---
    ["fluid-handling"] = {"oil-processing"},
    ["oil-processing"] = {"production-2"},
    ["advanced-oil-processing"] = {"oil-processing"},
    ["coal-liquefaction"] = {"oil-processing", "sulfur-processing", "carbon-processing-3"},
    ["lubricant"] = {"production-2"},
    ["sulfur-processing"] = {"oil-processing", "carbon-processing-2"},
    ["plastics"] = {"sulfur-processing"},
    --- Nuclear ---
    ["uranium-processing"] = {"ore-processing-2", "power-3"},
    ["nuclear-power"] = {"uranium-processing"},
    ["kovarex-enrichment-process"] = {"uranium-processing"},
    ["nuclear-fuel-reprocessing"] = {"nuclear-power", "kovarex-enrichment-process"},

    -- Modules --
    ["modules"] = {"effect-transmission"},
    ["speed-module"] = {"production-2", "modules"},
    ["speed-module-2"] = {"silver-processing-1", "production-3", "speed-module"},
    ["speed-module-3"] = {"titanium-processing-2", "production-4", "speed-module-2"},
    ["speed-module-4"] = {"tungsten-processing-1", "production-5", "speed-module-3"},
    ["speed-module-5"] = {"gold-processing-3", "tungsten-processing-2", "metal-processing-5", "speed-module-4"},
    ["productivity-module"] = {"production-2", "modules"},
    ["productivity-module-2"] = {"silver-processing-1", "production-3", "productivity-module"},
    ["productivity-module-3"] = {"titanium-processing-2", "production-4", "productivity-module-2"},
    ["productivity-module-4"] = {"tungsten-processing-1", "production-5", "productivity-module-3"},
    ["productivity-module-5"] = {"gold-processing-3", "tungsten-processing-2", "metal-processing-5", "productivity-module-4"},
    ["effectivity-module"] = {"production-2", "modules"},
    ["effectivity-module-2"] = {"silver-processing-1", "production-3", "effectivity-module"},
    ["effectivity-module-3"] = {"titanium-processing-2", "production-4", "effectivity-module-2"},
    ["effectivity-module-4"] = {"tungsten-processing-1", "production-5", "effectivity-module-3"},
    ["effectivity-module-5"] = {"gold-processing-3", "tungsten-processing-2", "metal-processing-5", "effectivity-module-4"},

    -- Space Technologies --
    ["low-density-structure"] = {"production-4"},
    ["rocket-control-unit"] = {"advanced-material-processing-2", "production-3"},
    ["rocketry"] = {"low-density-structure", "rocket-fuel", "rocket-control-unit"},
    ["rocket-silo"] = {"landfill", "rocketry", "lubricant"},
    ["space-technology"] = {"titanium-processing-1", "power-3", "logistics-2", "automation-3", "production-3", "rocket-silo"},

    -- Intermediates --
    ["electronics"] = {"production-1"},
    ["battery"] = {"production-3"},
    ["engine"] = {"production-2"},
    ["electric-engine"] = {"engine", "production-3", "plastics"},
    ["advanced-electronics"] = {"electronics", "production-2"},
    ["advanced-electronics-2"] = {"advanced-electronics", "production-3"},


    -- Unsorted --
    ["stack-inserter"] = {"automation-3", "fast-inserter"},
    ["automobilism"] = {"transportation-1", "logistics-2"},
    ["gun-turret"] = {"military"},
    ["concrete"] = {"logistics"},
    ["gate"] = {"electronics", "stone-wall"},
    ["rail-signals"] = {"automated-rail-transport"},
    ["stone-wall"] = {"military"},
    ["tank"] = {"automobilism", "military-3"},
    ["fluid-wagon"] = {"railway", "fluid-handling"},
    ["rocket-fuel"] = {"production-4", "carbon-processing-3"},
    ["steel-axe"] = {"production-1"},
    ["automated-rail-transport"] = {"railway", "transportation-3"},
    ["landfill"] = {"concrete"},
    ["fast-inserter"] = {"automation"},
    ["railway"] = {"engine", "transportation-2"},
    ["optics"] = {"production-1", "infrastructure", "automation"},
    ["robotics"] = {"logistics-3", "transportation-3"},
    ["laser"] = {"advanced-electronics"},
    ["effect-transmission"] = {"electric-energy-distribution-1", "production-3", "power-3"},
    ["logistic-system"] = {"logistic-robots",  "construction-robots"},
    ["logistic-robots"] = {"battery", "robotics"},
    ["construction-robots"] = {"battery", "robotics"},
    
}

-- TODO Add all technology icons
DyWorld_2_Main_Tech_Icons = {
    -- Stuff will be added automatically below here if it is not already present --
    --[""] = {},

    ["hematite-processing-1"] = {{{icon = Dy_icon_ore.."hematite.png"},{icon = Dy_looped.."1.png"}}, 64},
    ["hematite-processing-2"] = {{{icon = Dy_icon_ore.."hematite.png"},{icon = Dy_looped.."2.png"}}, 64},
    ["hematite-processing-3"] = {{{icon = Dy_icon_ore.."hematite.png"},{icon = Dy_looped.."3.png"}}, 64},
    ["hematite-processing-4"] = {{{icon = Dy_icon_ore.."hematite.png"},{icon = Dy_looped.."4.png"}}, 64},
    ["hematite-processing-5"] = {{{icon = Dy_icon_ore.."hematite.png"},{icon = Dy_looped.."5.png"}}, 64},
    ["chalcopyrite-processing-1"] = {{{icon = Dy_icon_ore.."chalcopyrite.png"},{icon = Dy_looped.."1.png"}}, 64},
    ["chalcopyrite-processing-2"] = {{{icon = Dy_icon_ore.."chalcopyrite.png"},{icon = Dy_looped.."2.png"}}, 64},
    ["chalcopyrite-processing-3"] = {{{icon = Dy_icon_ore.."chalcopyrite.png"},{icon = Dy_looped.."3.png"}}, 64},
    ["chalcopyrite-processing-4"] = {{{icon = Dy_icon_ore.."chalcopyrite.png"},{icon = Dy_looped.."4.png"}}, 64},
    ["chalcopyrite-processing-5"] = {{{icon = Dy_icon_ore.."chalcopyrite.png"},{icon = Dy_looped.."5.png"}}, 64},
    ["metallurgy"] = {{{icon = Dy_tech.."metallurgy.png"}}, 256},
    ["ore-processing-1"] = {{{icon = Dy_tech.."metallurgy.png"}}, 256},
    ["ore-processing-2"] = {{{icon = Dy_tech.."metallurgy.png"}}, 256},
    ["ore-processing-3"] = {{{icon = Dy_tech.."metallurgy.png"}}, 256},
    ["ore-processing-4"] = {{{icon = Dy_tech.."metallurgy.png"}}, 256},
    ["ore-processing-5"] = {{{icon = Dy_tech.."metallurgy.png"}}, 256},
    ["metal-processing-1"] = {{{icon = Dy_tech.."slag.png"}}, 256},
    ["metal-processing-2"] = {{{icon = Dy_tech.."slag.png"}}, 256},
    ["metal-processing-3"] = {{{icon = Dy_tech.."slag.png"}}, 256},
    ["metal-processing-4"] = {{{icon = Dy_tech.."slag.png"}}, 256},
    ["metal-processing-5"] = {{{icon = Dy_tech.."slag.png"}}, 256},
    ["alloying-1"] = {{{icon = Dy_tech.."slag.png"}}, 256},
    ["alloying-2"] = {{{icon = Dy_tech.."slag.png"}}, 256},
    ["alloying-3"] = {{{icon = Dy_tech.."slag.png"}}, 256},
    ["alloying-4"] = {{{icon = Dy_tech.."slag.png"}}, 256},
    ["alloying-5"] = {{{icon = Dy_tech.."slag.png"}}, 256},
    ["iron-processing-1"] = {{{icon = Dy_tech.."iron.png"}}, 256},
    ["iron-processing-2"] = {{{icon = Dy_tech.."iron.png"}}, 256},
    ["iron-processing-3"] = {{{icon = Dy_tech.."iron.png"}}, 256},
    ["iron-processing-4"] = {{{icon = Dy_tech.."iron.png"}}, 256},
    ["copper-processing-1"] = {{{icon = Dy_tech.."copper.png"}}, 256},
    ["copper-processing-2"] = {{{icon = Dy_tech.."copper.png"}}, 256},
    ["copper-processing-3"] = {{{icon = Dy_tech.."copper.png"}}, 256},
    ["copper-processing-4"] = {{{icon = Dy_tech.."copper.png"}}, 256},
    ["tin-processing-1"] = {{{icon = Dy_tech.."tin.png"}}, 256},
    ["tin-processing-2"] = {{{icon = Dy_tech.."tin.png"}}, 256},
    ["tin-processing-3"] = {{{icon = Dy_tech.."tin.png"}}, 256},
    ["tin-processing-4"] = {{{icon = Dy_tech.."tin.png"}}, 256},
    ["silver-processing-1"] = {{{icon = Dy_tech.."silver.png"}}, 256},
    ["silver-processing-2"] = {{{icon = Dy_tech.."silver.png"}}, 256},
    ["silver-processing-3"] = {{{icon = Dy_tech.."silver.png"}}, 256},
    ["silver-processing-4"] = {{{icon = Dy_tech.."silver.png"}}, 256},
    ["titanium-processing-1"] = {{{icon = Dy_tech.."titanium.png"}}, 256},
    ["titanium-processing-2"] = {{{icon = Dy_tech.."titanium.png"}}, 256},
    ["titanium-processing-3"] = {{{icon = Dy_tech.."titanium.png"}}, 256},
    ["aluminium-processing-1"] = {{{icon = Dy_tech.."aluminium.png"}}, 256},

    
}

for k,v in pairs(DyWorld_2_Main_Tech) do
    if not DyWorld_2_Main_Tech_Icons[k] then
        DyWorld_2_Main_Tech_Icons[k] = {{{icon = "__DyCore__/graphics/questionmark.png"}}, 64}
    end
end