

Story_0_Data = {
	unlocks_recipes = {
		"charcoal-basic",
		"stone-brick-basic-1",
		"stone-brick-basic-2",
		"stone-brick-basic-3",
		"stone-brick-basic-4",
		"basic-kiln",
		"small-storage",
	}
}

Story_ExtraTechs_Table_Base = {
	["story_tech_minimap"] = {
		effects = {
			{
				effect_description = {"technology-description.story_tech_minimap_extra"},
			},
		},
	},
}

-- STB[act][phase]
-- 		.amount
-- 			[1] = main objective count
--			[2] = side objective count
-- 			[3] = total objective
Story_Table_Base  = {
	[1] = {
		[1] = {
			done = false,
			started = true,
			amount = {5, 0, 5}, -- hardcoded for A1-P1 b/c PhaseForward is not called when starting it
			message = 3,
			objectives = {
				[1] = {
					type_1 = "looted",
					type_2 = "item",
					name = "9mm-pistol",
					amount_needed = 1,
					amount_done = 0,
					set_stone = true,
					done = false,
				},
				[2] = {
					type_1 = "build",
					type_2 = "name",
					name = "basic-kiln",
					amount_needed = 4,
					amount_done = 0,
					set_stone = true,
					done = false,
				},
				[3] = {
					type_1 = "mine",
					type_2 = "item",
					name = "limestone",
					amount_needed = 40,
					amount_done = 0,
					set_stone = true,
					done = false,
				},
				[4] = {
					type_1 = "mine",
					type_2 = "item",
					name = "wood",
					amount_needed = 50,
					amount_done = 0,
					set_stone = true,
					done = false,
				},
				[5] = {
					type_1 = "craft",
					type_2 = "item",
					name = "small-storage",
					amount_needed = 5,
					amount_done = 0,
					set_stone = true,
					done = false,
				},
			},
			unlocks_recipes = {
				"bronze-basic",
				"9mm-bullet-bronze",
				"9mm-mag-bronze",
				"9mm-mag-bronze-del",
				"9mm-pistol",
				"basic-burner-drill",
				"basic-med-pack",
			},
			-- gives_items = {
			-- 	["9mm-pistol"] = 1,
			-- 	["9mm-mag-iron"] = 10,
			-- 	["med-pack"] = 10,
			-- }
		},
		[2] = {
			done = false,
			started = false,
			message = 3,
			objectives = {
				[1] = {
					type_1 = "position",
					type_2 = "enemy-find",
					type_3 = 500,
					done = false,
					PosX = 0,
					PosY = 0,
					Surface = "nauvis",
					Tag = "Dy-Story-Tag-1",
				},
				[2] = {
					type_1 = "build",
					type_2 = "name",
					name = "basic-burner-drill",
					amount_needed = 10,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[3] = {
					type_1 = "looted",
					type_2 = "item",
					name = "bronze-plate",
					amount_needed = 5,
					amount_done = 0,
					done = false,
				}
			},
			unlocks_recipes = {
				"stone-brick-wall",
				"basic-9mm-turret",
				"basic-armor",
			},
			label = {"explore"},
		},
		[3] = {
			done = false,
			started = false,
			message = 2,
			objectives = {
				[1] = {
					type_1 = "craft",
					type_2 = "item",
					name = "basic-armor",
					amount_needed = 2,
					amount_done = 0,
					done = false,
				},
				[2] = {
					type_1 = "build",
					type_2 = "name",
					name = "stone-brick-wall",
					amount_needed = 50,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[3] = {
					type_1 = "build",
					type_2 = "name",
					name = "basic-9mm-turret",
					amount_needed = 5,
					amount_done = 0,
                    random = true,
					done = false,
				},
			},
			unlocks_recipes = {
				"basic-treefarm",
				"rain-collecting",
				"rain-collector",
				"offshore-pump",
				"burner-turbine",
				"basic-power-pole",
				"bronze-pipe",
				"bronze-pipe-to-ground",
				"basic-repair-pack",
			},
		},
		[4] = {
			done = false,
			started = false,
			message = 2,
			objectives = {
				[1] = {
					type_1 = "craft",
					type_2 = "item",
					name = "offshore-pump",
					amount_needed = 1,
					amount_done = 0,
                    set_stone = true,
					done = false,
				},
				[2] = {
					type_1 = "craft",
					type_2 = "item",
					name = "bronze-pipe",
					amount_needed = 20,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[3] = {
					type_1 = "build",
					type_2 = "name",
					name = "basic-treefarm",
					amount_needed = 4,
					amount_done = 0,
                    random = true,
					done = false,
				},
			},
			unlocks_recipes = {
				"transport-belt-1",
				"underground-belt-1",
				"splitter-1",
				"burner-inserter",
				"bronze-gear",
			},
		},
		[5] = {
			done = false,
			started = false,
			message = 2,
			objectives = {
				[1] = {
					type_1 = "craft",
					type_2 = "item",
					name = "burner-inserter",
					amount_needed = 5,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[2] = {
					type_1 = "craft",
					type_2 = "item",
					name = "bronze-gear",
					amount_needed = 20,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[3] = {
					type_1 = "build",
					type_2 = "name",
					name = "transport-belt-1",
					amount_needed = 25,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[4] = {
					type_1 = "position",
					done = false,
					PosX = 0,
					PosY = 0,
					Surface = "nauvis",
				},
			},
			unlocks_recipes = {
				"burner-assembler",
				"loader-1",
				"control-board-1",
				"stone-brick-gate",
				"tin-basic",
				"tin-basic-2",
				"9mm-bullet-tin",
				"9mm-mag-tin",
				"9mm-mag-tin-del",
			},
		},
		[6] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 2,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 40,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[2] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit-spawner",
					amount_needed = 3,
					amount_done = 0,
					done = false,
				},
				[3] = {
					type_1 = "build",
					type_2 = "name",
					name = "burner-assembler",
					amount_needed = 4,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[4] = {
					type_1 = "position",
					type_2 = "enemy-find",
					type_3 = 500,
					done = false,
					PosX = 0,
					PosY = 0,
					Surface = "nauvis",
					Tag = "Dy-Story-Tag-1",
				},
			},
			unlocks_recipes = {
				"green-wire",
				"red-wire",
				"med-pack",
			},
		},
		[7] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 2,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 60,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[2] = {
					type_1 = "craft",
					type_2 = "item",
					name = "med-pack",
					amount_needed = 2,
					amount_done = 0,
                    set_stone = true,
					done = false,
				},
			},
			unlocks_recipes = {
				"cast-iron-1",
				"cast-iron-1b",
				"cast-copper-1",
				"cast-copper-1b",
				"small-storage-2",
				"iron-gear",
				"copper-cable",
				"9mm-bullet-copper",
				"9mm-mag-copper",
				"9mm-mag-copper-del",
			},
			label = {"wait"},
		},
		[8] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 2,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 75,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[2] = {
					type_1 = "craft",
					type_2 = "item",
					name = "copper-cable",
					amount_needed = 5,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[3] = {
					type_1 = "craft",
					type_2 = "item",
					name = "iron-gear",
					amount_needed = 4,
					amount_done = 0,
                    random = true,
					done = false,
				},
			},
			unlocks_recipes = {
				"basic-power-armor",
				"ammo-nano-constructors",
				"gun-nano-emitter",
			},
			label = {"wait"},
			sounds = {"DySound_future_sounds_1"},
		},
		[9] = {
			done = false,
			started = false,
			message = 2,
			objectives = {
				[1] = {
					type_1 = "craft",
					type_2 = "item",
					name = "basic-power-armor",
					amount_needed = 1,
					amount_done = 0,
                    set_stone = true,
					done = false,
				},
				[2] = {
					type_1 = "craft",
					type_2 = "item",
					name = "ammo-nano-constructors",
					amount_needed = 1,
					amount_done = 0,
                    set_stone = true,
					done = false,
				},
			},
			unlocks_recipes = {
				"basic-assembler",
				"burner-radar",
				"lab-1",
				"basic-electric-drill",
				"basic-boiler",
				"basic-steam-engine",
				"solar-panel-equipment-1",
				"belt-immunity-equipment",
				"9mm-bullet-iron",
				"9mm-mag-iron",
				"9mm-mag-iron-del",
				"car-1",
				"boat-1",
			},
		},
		[10] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 5,
			objectives = {
				[1] = {
					type_1 = "build",
					type_2 = "name",
					name = "lab-1",
					amount_needed = 1,
					amount_done = 0,
					set_stone = true,
					done = false,
				},
				[2] = {
					type_1 = "build",
					type_2 = "name",
					name = "basic-boiler",
					amount_needed = 10,
					amount_done = 0,
					set_stone = true,
					done = false,
				},
				[3] = {
					type_1 = "build",
					type_2 = "name",
					name = "basic-steam-engine",
					amount_needed = 20,
					amount_done = 0,
					set_stone = true,
					done = false,
				},
				[4] = {
					type_1 = "build",
					type_2 = "name",
					name = "basic-electric-drill",
					amount_needed = 4,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[5] = {
					type_1 = "build",
					type_2 = "name",
					name = "basic-assembler",
					amount_needed = 4,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[6] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 300,
					amount_done = 0,
                    random = true,
					done = false,
				},
			},
			sounds = {"DySound_drone_1"},
		},
		[11] = {
			done = false,
			started = false,
			location_objective = true,
			objectives = {
				[1] = {
					type_1 = "position",
					done = false,
					PosX = 0,
					PosY = 0,
					Surface = "nauvis",
				},
			},
		},
	},
	[2] = {
		[1] = {
			done = false,
			started = false,
			message = 1,
			objectives = {
				[1] = {
					type_1 = "corpse",
					type_2 = "corpse",
					name = "corpse",
					done = false,
				},
			},
			label = {"corpse"},
			sounds = {"DySound_nuclear_alarm"},
		},
		[2] = {
			done = false,
			started = false,
			message = 1,
			objectives = {
				[1] = {
					type_1 = "research",
					type_2 = "name",
					name = "copper-processing",
					done = false,
				},
				[2] = {
					type_1 = "research",
					type_2 = "name",
					name = "iron-processing",
					done = false,
				},
				[3] = {
					type_1 = "research",
					type_2 = "name",
					name = "tin-processing",
					done = false,
				},
			},
			unlocks_recipes = {
				"lab-2",
				"lab-4",
				"food-implant",
				"small-storage-3",
			},
			label = {"rebuild"},
		},
		[3] = {
			done = false,
			started = false,
			message = 1,
			objectives = {
				[1] = {
					type_1 = "world",
					type_2 = "radar-scan",
					done = false,
					amount_needed = 500,
					amount_done = 0,
                    random = true,
				},
			},
			unlocks_recipes = {
				"health-implant",
			},
			label = {"rebuild", "buildup"},
		},
		[4] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 1,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 500,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[2] = {
					type_1 = "world",
					type_2 = "radar-scan",
					amount_needed = 1000,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[3] = {
					type_1 = "world",
					type_2 = "chunk",
					amount_needed = 250,
					amount_done = 0,
					set_stone = true,
					done = false,
				},
			},
			label = {"buildup"},
		},
		[5] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 2,
			objectives = {
				[1] = {
					type_1 = "build",
					type_2 = "name",
					name = "lab-2",
					amount_needed = 1,
					amount_done = 0,
                    set_stone = true,
					done = false,
				},
				[2] = {
					type_1 = "build",
					type_2 = "name",
					name = "blast-furnace",
					amount_needed = 10,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[3] = {
					type_1 = "build",
					type_2 = "name",
					name = "oil-refinery",
					amount_needed = 5,
					amount_done = 0,
                    random = true,
					done = false,
				},
			},
		},
		[6] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 1,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 1000,
					amount_done = 0,
                    random = true,
					done = false,
				},
			},
		},
		[7] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 1,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 1000,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[2] = {
					type_1 = "research",
					type_2 = "name",
					name = "automatica-3",
					done = false,
				},
			},
		},
		[8] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 1,
			objectives = {
				[1] = {
					type_1 = "research",
					type_2 = "name",
					name = "space-mining",
					done = false,
				},
			},
			unlocks_recipes = {
				"asteroid-miner-titanium",
				"lab-3",
			},
		},
		[9] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 1,
			objectives = {
				[1] = {
					type_1 = "research",
					type_2 = "name",
					name = "basic-asteroid-mining",
					done = false,
				},
				[2] = {
					type_1 = "launch",
					type_2 = "rocket",
					amount_needed = 5,
					amount_done = 0,
                    set_stone = true,
					done = false,
				},
			},
			label = {"space-mining"},
		},
		[10] = {
			done = false,
			started = false,
			attack = {"nauvis", "player"},
			message = 1,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 500,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[2] = {
					type_1 = "launch",
					type_2 = "rocket",
					amount_needed = 500,
					amount_done = 0,
                    random = true,
					done = false,
				},
			},
			label = {"space-mining"},
		},
	},
	[3] = {
		[1] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 2,
			objectives_side = true,
			objectives = {
				[1] = {
					type_1 = "research",
					type_2 = "name",
					name = "automatica-4",
					done = false,
				},
				[2] = {
					type_1 = "research",
					type_2 = "name",
					name = "fuel-processing",
					done = false,
				},
			},
		},
		[2] = {
			done = false,
			started = false,
			attack = {"nauvis", "player"},
			message = 3,
			objectives_side = true,
			objectives = {
				[1] = {
					type_1 = "research",
					type_2 = "name",
					name = "automatica-6",
					done = false,
				},
				[2] = {
					type_1 = "research",
					type_2 = "name",
					name = "se-lifesupport-facility",
					done = false,
				},
			},
			sounds = {"DySound_drone_1"},
		},
		[3] = {
			done = false,
			started = false,
			attack = {"nauvis", "player"},
			message = 3,
			objectives_side = true,
			objectives = {
				[1] = {
					type_1 = "research",
					type_2 = "name",
					name = "se-thruster-suit",
					done = false,
				},
			},
			sounds = {"DySound_drone_1"},
		},
		[4] = {
			done = false,
			started = false,
			attack = {"nauvis", "player"},
			message = 3,
			objectives_side = true,
			objectives = {
				[1] = {
					type_1 = "research",
					type_2 = "name",
					name = "se-rocket-launch-pad",
					done = false,
				},
				[2] = {
					type_1 = "research",
					type_2 = "name",
					name = "se-space-platform-scaffold",
					done = false,
				},
				[3] = {
					type_1 = "build",
					type_2 = "name",
					name = "se-rocket-launch-pad",
					amount_needed = 1,
					amount_done = 0,
                    set_stone = true,
					done = false,
				},
			},
			sounds = {"DySound_drone_1"},
		},
		[5] = {
			done = false,
			started = false,
			attack = {"player-ambush-101"},
			message = 3,
			objectives_side = true,
			objectives = {
				[1] = {
					type_1 = "build",
					type_2 = "name",
					name = "se-space-platform-scaffold",
					amount_needed = 250,
					amount_done = 0,
                    random = true,
					done = false,
				},
				[2] = {
					type_1 = "position",
					done = false,
					PosX = -90,
					PosY = -20,
					Surface = "Nauvis Orbit",
				},
			},
		},
		[6] = {
			done = false,
			started = false,
			attack = {"player-ambush-101"},
			message = 1,
			objectives_side = true,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 999999999,
					amount_done = 0,
					done = false,
				},
				[2] = {
					type_1 = "position",
					done = false,
					PosX = 0,
					PosY = 0,
					Surface = "nauvis",
				},
			},
		},
		[7] = {
			done = false,
			started = false,
			attack = {"nauvis", "player-ambush-101"},
			message = 1,
			objectives_side = true,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 999999999,
					amount_done = 0,
					done = false,
				},
			},
			label = {"story-wip"},
		},
		[8] = {
			done = false,
			started = false,
			attack = {"nauvis", "player-ambush-101"},
			message = 1,
			objectives_side = true,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 999999999,
					amount_done = 0,
					done = false,
				},
			},
			label = {"story-wip"},
		},
		[9] = {
			done = false,
			started = false,
			attack = {"nauvis", "player-ambush-101"},
			message = 1,
			objectives_side = true,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 999999999,
					amount_done = 0,
					done = false,
				},
			},
			label = {"story-wip"},
		},
		[10] = {
			done = false,
			started = false,
			attack = {"player-ambush-101"},
			message = 1,
			objectives_side = true,
			objectives = {
			},
			label = {"story-wip"},
		},
		[11] = {
			done = false,
			started = false,
			attack = {"nauvis", "player-ambush-101"},
			message = 1,
			objectives_side = true,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 999999999,
					amount_done = 0,
					done = false,
				},
			},
			label = {"story-wip"},
		},
		-- [12] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [13] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [14] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [15] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [16] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [17] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [18] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [19] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [20] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [21] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [22] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [23] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [24] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "position",
		-- 			done = false,
		-- 			PosX = 0,
		-- 			PosY = 0,
		-- 			Surface = "Shakok",
		-- 		},
		-- 		[2] = {
		-- 			type_1 = "position",
		-- 			done = false,
		-- 			PosX = 0,
		-- 			PosY = 0,
		-- 			Surface = "Aine",
		-- 		},
		-- 		[3] = {
		-- 			type_1 = "position",
		-- 			done = false,
		-- 			PosX = 0,
		-- 			PosY = 0,
		-- 			Surface = "Kothar",
		-- 		},
		-- 		[4] = {
		-- 			type_1 = "position",
		-- 			done = false,
		-- 			PosX = 0,
		-- 			PosY = 0,
		-- 			Surface = "Enlil",
		-- 		},
		-- 		[5] = {
		-- 			type_1 = "position",
		-- 			done = false,
		-- 			PosX = 0,
		-- 			PosY = 0,
		-- 			Surface = "Freyr",
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [25] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- 	label = {"story-wip"},
		-- },
		-- [26] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [27] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [28] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [29] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [30] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [31] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis", "player"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [32] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [33] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [34] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [35] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [36] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [37] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [38] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [39] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [40] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [41] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [42] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [43] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [44] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [45] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [46] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [47] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [48] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [49] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
		-- [50] = {
		-- 	done = false,
		-- 	started = false,
		-- 	attack = {"nauvis"},
		-- 	message = 1,
		-- 	objectives_side = true,
		-- 	objectives = {
		-- 		[1] = {
		-- 			type_1 = "died",
		-- 			type_2 = "type",
		-- 			name = "unit",
		-- 			amount_needed = 999999999,
		-- 			amount_done = 0,
		-- 			done = false,
		-- 		},
		-- 	},
		-- },
	},
	[4] = {
		[1] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 1,
			objectives_side = true,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 999999999,
					amount_done = 0,
					done = false,
				},
			},
		},
	},
	[5] = {
		[1] = {
			done = false,
			started = false,
			attack = {"nauvis"},
			message = 1,
			objectives_side = true,
			objectives = {
				[1] = {
					type_1 = "died",
					type_2 = "type",
					name = "unit",
					amount_needed = 999999999,
					amount_done = 0,
					done = false,
				},
			},
		},
	},
}

-- Temp additions for act 4 and 5 --
--[[
for i = 1,50 do
	Story_Table_Base[4][i] = {
		done = false,
		started = false,
		attack = {"nauvis"},
		message = 1,
		objectives_side = true,
		objectives = {
			[1] = {
				type_1 = "died",
				type_2 = "type",
				name = "unit",
				amount_needed = 999999999,
				amount_done = 0,
				done = false,
			},
		},
	}
	Story_Table_Base[5][i] = {
		done = false,
		started = false,
		attack = {"nauvis"},
		message = 1,
		objectives_side = true,
		objectives = {
			[1] = {
				type_1 = "died",
				type_2 = "type",
				name = "unit",
				amount_needed = 999999999,
				amount_done = 0,
				done = false,
			},
		},
	}
end
]]
