on: push
name: Create Zip DyWorld
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Factorio Mod packaging
        uses: Roang-zero1/factorio-mod-package@v1.2.2
        with:
          mod_base_dir: .DyWorld-Dynamics
